networks:
  backend:

services:
  postgresql:
    container_name: scrapper-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scrapper
    ports:
      - "5432:5432"
    volumes:
        - ../postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d scrapper" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  liquibase-migrations:
    image: liquibase:latest
    restart: on-failure
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=root
      - --password=root
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ../volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

  bot:
    container_name: bot_container
    image: bot_image
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../env/bot.env
    networks:
      - backend
    deploy:
      restart_policy:
        delay: 5s
        condition: on-failure
        max_attempts: 5

  scrapper:
    container_name: scrapper_container
    image: scrapper_image
    build:
      context: .
      dockerfile: ./scrapper/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../env/scrapper.env
    networks:
      - backend
    deploy:
      restart_policy:
        delay: 5s
        condition: on-failure
        max_attempts: 5