CREATE TABLE CHAT (
    id BIGINT PRIMARY KEY NOT NULL,
    chat_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE LINK (
    id BIGINT PRIMARY KEY NOT NULL,
    url VARCHAR(255) NOT NULL,
    chat BIGINT REFERENCES CHAT(id) ON DELETE CASCADE,
    last_update TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);