app:
  test: test
  scheduler:
    interval: PT60S  # 1 минута
  database-access-type:
    jpa
  use-queue: true

scheduler:
  update: 86400000 # 1 день

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_updates: true
        order_insert: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST}
    username: guest
    password: guest
    port: 5672

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  githubBaseUrl: https://api.github.com
  stackoverflowBaseUrl: https://api.stackexchange.com/2.3
  botBaseUrl: http://localhost:8080

api:
  github:
    token: ${GITHUB_TOKEN}

rabbit:
  queue: scrapper-queue
  exchange: scrapper-exchange