app:
  test: test
  scheduler:
    interval: PT60S  # 1 минута

scheduler:
  update: 86400000 # 1 день

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  githubBaseUrl: https://api.github.com
  stackoverflowBaseUrl: https://api.stackexchange.com/2.3
  botBaseUrl: http://localhost:8080