app:
  test: test
  scheduler:
    interval: PT10S  # 10 секунд

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

default:
  timeout: 30

baseUrl:
  github: https://api.github.com
  stackOverflow: https://api.stackexchange.com/2.3