app:
  test: test
  token: ${BOT_TOKEN}

client:
  scrapperBaseUrl: ${SCRAPPER_URL}

spring:
  application:
    name: bot
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

rabbit:
  queue: scrapper-queue
  exchange: scrapper-exchange