app:
  test: test
  token: ${BOT_TOKEN}

baseUrl:
  scrapper: ${SCRAPPER_URL}

spring:
  application:
    name: bot
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false