name: scrapper CI/CD

on:
  push:
    paths:
      - 'scrapper/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/scrapper.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build scrapper module with Gradle
        run: ./gradlew :scrapper:build